#!/usr/bin/env bash
# Sigil A/B experiment harness — ILO-415
# Tests >> (variant A, current) vs -> (variant B, proposed) as pipe operator.
#
# Each task is run against both variants. Variant A uses current syntax.
# Variant B files are auto-generated by s/>>/->/ substitution.
#
# Outputs: results printed to stdout + research/sigil-ab/results.json
#
# Usage: ./research/sigil-ab/run.sh [--ilo PATH] [--tasks DIR]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
TASKS_DIR="$SCRIPT_DIR/tasks"
RESULTS_JSON="$SCRIPT_DIR/results.json"

# ── Parse flags ──────────────────────────────────────────────────────────────
ILO="${ILO:-}"
for arg in "$@"; do
    case "$arg" in
        --ilo=*)  ILO="${arg#--ilo=}" ;;
        --tasks=*) TASKS_DIR="${arg#--tasks=}" ;;
    esac
done

# ── Locate ilo binary ────────────────────────────────────────────────────────
if [[ -z "$ILO" ]]; then
    CARGO_TARGET_DIR="${CARGO_TARGET_DIR:-/tmp/target-415}"
    if [[ -x "$CARGO_TARGET_DIR/debug/ilo" ]]; then
        ILO="$CARGO_TARGET_DIR/debug/ilo"
    elif [[ -x "$CARGO_TARGET_DIR/release/ilo" ]]; then
        ILO="$CARGO_TARGET_DIR/release/ilo"
    else
        echo "Building ilo (debug)..."
        cd "$REPO_ROOT"
        CARGO_TARGET_DIR="$CARGO_TARGET_DIR" cargo build 2>&1 | tail -3
        ILO="$CARGO_TARGET_DIR/debug/ilo"
    fi
fi

if [[ ! -x "$ILO" ]]; then
    echo "ERROR: ilo binary not found. Provide --ilo=PATH or set ILO= env var." >&2
    exit 1
fi

echo "Using ilo: $ILO"
echo "Tasks dir: $TASKS_DIR"
echo ""

# ── Task definitions ─────────────────────────────────────────────────────────
# Format: "task_file | func | args | expected_output"
declare -a TASKS=(
    "t01-basic-pipe.ilo|main|3|49"
    "t02-pipe-with-list.ilo|main|[1,-2,3,-4,5]|[1, 9, 25]"
    "t03-pipe-str-transform.ilo|word-len|hello|5"
    "t04-pipe-paren-wrap.ilo|add-piped|3 4|11"
    "t05-pipe-multiline.ilo|num-len|12345|5"
)

# ── Helper: approximate token count (bytes/3.4, matches tokcount builtin) ───
tokcount() {
    local file="$1"
    local chars
    # Count only non-comment, non-blank lines
    chars=$(grep -v "^--" "$file" | grep -v "^$" | wc -c)
    python3 -c "print(round($chars / 3.4))"
}

# ── Helper: run a single task variant ───────────────────────────────────────
# Returns: "pass|fail" and fills globals LAST_OUTPUT, LAST_ERROR
run_task() {
    local file="$1" func="$2" args="$3" expected="$4"

    # Step 1: check (parse + type-check)
    local check_out
    check_out=$("$ILO" check "$file" 2>&1) || true
    if [[ -n "$check_out" ]]; then
        local err_code
        err_code=$(echo "$check_out" | python3 -c "
import sys, json
try:
    d = json.loads(sys.stdin.read())
    print(d.get('code', 'UNKNOWN'))
except:
    print('PARSE_FAIL')
" 2>/dev/null)
        LAST_OUTPUT=""
        LAST_ERROR="check_fail:$err_code"
        return 1
    fi

    # Step 2: run
    local run_out
    # shellcheck disable=SC2086
    run_out=$("$ILO" "$file" "$func" $args 2>&1) || true
    LAST_OUTPUT="$run_out"

    if [[ "$run_out" == "$expected" ]]; then
        LAST_ERROR=""
        return 0
    else
        LAST_ERROR="wrong_output:got '$run_out' expected '$expected'"
        return 1
    fi
}

# ── Main experiment loop ──────────────────────────────────────────────────────
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ILO-415 Sigil A/B Experiment: >> (Var A) vs -> (Var B)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

declare -a JSON_ROWS=()

printf "%-32s %6s %8s %8s %8s %8s\n" "Task" "Tokens" "A:check" "A:run" "B:check" "B:run"
printf "%-32s %6s %8s %8s %8s %8s\n" "----" "------" "-------" "-----" "-------" "-----"

a_pass=0; a_fail=0
b_pass=0; b_fail=0

for task_def in "${TASKS[@]}"; do
    IFS='|' read -r task_file func args expected <<< "$task_def"
    a_file="$TASKS_DIR/$task_file"
    b_file="$TASKS_DIR/${task_file%.ilo}-varB.ilo"

    # Ensure variant B exists
    if [[ ! -f "$b_file" ]]; then
        sed 's/>>/\->/g' "$a_file" > "$b_file"
    fi

    tokens=$(tokcount "$a_file")

    # Run variant A
    LAST_OUTPUT="" LAST_ERROR=""
    if run_task "$a_file" "$func" "$args" "$expected"; then
        a_check="PASS"; a_run="PASS"; ((a_pass++)) || true
        a_check_detail="ok"; a_run_detail="ok"
    else
        if [[ "$LAST_ERROR" == check_fail:* ]]; then
            a_check="FAIL"; a_run="SKIP"
            a_check_detail="${LAST_ERROR#check_fail:}"; a_run_detail="skipped"
            ((a_fail++)) || true
        else
            a_check="PASS"; a_run="FAIL"
            a_check_detail="ok"; a_run_detail="$LAST_ERROR"
            ((a_fail++)) || true
        fi
    fi

    # Run variant B
    LAST_OUTPUT="" LAST_ERROR=""
    if run_task "$b_file" "$func" "$args" "$expected"; then
        b_check="PASS"; b_run="PASS"; ((b_pass++)) || true
        b_check_detail="ok"; b_run_detail="ok"
    else
        if [[ "$LAST_ERROR" == check_fail:* ]]; then
            b_check="FAIL"; b_run="SKIP"
            b_check_detail="${LAST_ERROR#check_fail:}"; b_run_detail="skipped"
            ((b_fail++)) || true
        else
            b_check="PASS"; b_run="FAIL"
            b_check_detail="ok"; b_run_detail="$LAST_ERROR"
            ((b_fail++)) || true
        fi
    fi

    label="${task_file%.ilo}"
    printf "%-32s %6s %8s %8s %8s %8s\n" "$label" "$tokens" "$a_check" "$a_run" "$b_check" "$b_run"

    # Build JSON row
    JSON_ROWS+=("{\"task\":\"$label\",\"tokens\":$tokens,\"varA\":{\"check\":\"$a_check\",\"run\":\"$a_run\",\"check_detail\":\"$a_check_detail\",\"run_detail\":\"$a_run_detail\"},\"varB\":{\"check\":\"$b_check\",\"run\":\"$b_run\",\"check_detail\":\"$b_check_detail\",\"run_detail\":\"$b_run_detail\"}}")
done

echo ""
echo "Summary:"
echo "  Variant A (>>): $a_pass pass, $a_fail fail"
echo "  Variant B (->): $b_pass pass, $b_fail fail"
echo ""

# Variant B failure analysis
echo "Variant B parse error categories:"
for task_def in "${TASKS[@]}"; do
    IFS='|' read -r task_file func args expected <<< "$task_def"
    b_file="$TASKS_DIR/${task_file%.ilo}-varB.ilo"
    result=$("$ILO" check "$b_file" 2>&1) || true
    if [[ -n "$result" ]]; then
        code=$(echo "$result" | python3 -c "import sys,json; d=json.loads(sys.stdin.read()); print(d.get('code','?'))" 2>/dev/null || echo "?")
        msg=$(echo "$result" | python3 -c "import sys,json; d=json.loads(sys.stdin.read()); print(d.get('message','?'))" 2>/dev/null || echo "?")
        echo "  ${task_file%.ilo}: $code — $msg"
    fi
done

# ── Write results.json ────────────────────────────────────────────────────────
python3 - "$RESULTS_JSON" "${JSON_ROWS[@]}" << 'PYEOF'
import sys, json, datetime

out_path = sys.argv[1]
rows = sys.argv[2:]

tasks = [json.loads(r) for r in rows]

output = {
    "generated": datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    "experiment": "ILO-415 sigil A/B: >> vs -> as pipe operator",
    "variants": {
        "A": ">> (current, baseline)",
        "B": "-> (proposed; not yet implemented — all B tasks expected to fail)"
    },
    "tasks": tasks,
    "summary": {
        "varA_pass": sum(1 for t in tasks if t["varA"]["run"] == "PASS"),
        "varA_fail": sum(1 for t in tasks if t["varA"]["run"] != "PASS"),
        "varB_pass": sum(1 for t in tasks if t["varB"]["check"] == "PASS"),
        "varB_fail": sum(1 for t in tasks if t["varB"]["check"] != "PASS"),
    }
}

with open(out_path, "w") as f:
    json.dump(output, f, indent=2)

print(f"Results written to {out_path}")
PYEOF

echo ""
echo "Done. Results: $RESULTS_JSON"
