//! Zero source emission helpers.
//!
//! Render functions that produce idiomatic Zero source from a small,
//! HIR-derived intermediate (currently just the list of strings to print).
//! Kept separate from `mod.rs` so the walker stays focused on HIR shape
//! and emission stays focused on Zero syntax.

/// Render a complete Zero program whose `main` writes each string in
/// `prints` to stdout in order. Each entry has `\n` appended, mirroring
/// ilo's `prnt` semantics.
///
/// The shape matches the pinned-toolchain capability matrix exactly:
///
/// ```zero
/// pub fun main(world: World) -> Void raises {
///     check world.out.write("hello\n")
/// }
/// ```
pub fn render_main(prints: &[String]) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by the ilo Zero backend (Phase 5 Stage 5e).\n");
    out.push_str("// Pinned: zero 0.1.2. Edit the .ilo source instead of this file.\n\n");
    out.push_str("pub fun main(world: World) -> Void raises {\n");
    if prints.is_empty() {
        // Empty main is valid Zero — emit a no-op body comment so the
        // output is still readable.
        out.push_str("    // no statements\n");
    } else {
        for s in prints {
            let escaped = escape_zero_string(s);
            out.push_str("    check world.out.write(\"");
            out.push_str(&escaped);
            out.push_str("\\n\")\n");
        }
    }
    out.push_str("}\n");
    out
}

/// Public wrapper for direct callers (e.g. tooling that wants the source
/// without writing to disk).
pub fn emit_to_string(prints: &[String]) -> String {
    render_main(prints)
}

/// Escape a string for Zero's double-quoted string literal syntax. Zero's
/// escape grammar matches ilo's near-1:1 (per the capability matrix), so
/// we handle the standard set.
fn escape_zero_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_hello() {
        let src = render_main(&["hello".to_string()]);
        assert!(src.contains("pub fun main(world: World) -> Void raises {"));
        assert!(src.contains("check world.out.write(\"hello\\n\")"));
    }

    #[test]
    fn render_multiple() {
        let src = render_main(&["a".to_string(), "b".to_string()]);
        let a = src.find("\"a\\n\"").expect("a present");
        let b = src.find("\"b\\n\"").expect("b present");
        assert!(a < b, "order preserved");
    }

    #[test]
    fn render_empty_body() {
        let src = render_main(&[]);
        assert!(src.contains("// no statements"));
    }

    #[test]
    fn escapes_quote_and_backslash() {
        let src = render_main(&["she said \"hi\\bye\"".to_string()]);
        assert!(src.contains("\\\"hi\\\\bye\\\""), "src: {}", src);
    }
}
