//! Package registry: `ilo add <owner>/<repo>[@<ref>]` / `ilo update`.
//!
//! Cache layout:  `~/.ilo/pkgs/<host>/<owner>/<repo>/`
//! Lockfile:      `ilo.lock` in the project root (current working directory).
//!
//! The lock file is a plain-text tabular format — one resolved package per line:
//!
//! ```
//! # ilo.lock — generated by `ilo add`; commit to source control
//! github:owner/repo  <sha40>  https://github.com/owner/repo
//! ```
//!
//! Columns are tab-separated.  Lines starting with `#` are comments.
//!
//! ## Supported host prefixes
//!
//! - `github:org/repo`   → https://github.com/org/repo  (also bare `org/repo`)
//! - `gitlab:org/repo`   → https://gitlab.com/org/repo
//! - `codeberg:user/repo`→ https://codeberg.org/user/repo
//! - `https://...`       → used verbatim
//!
//! ## `use "owner/repo"` resolution
//!
//! When `resolve_imports` sees a `use` path whose first component contains no
//! `.` (i.e. it looks like `owner/repo` not `./local.ilo`), it delegates to
//! `resolve_pkg_path` which returns `~/.ilo/pkgs/<host>/<owner>/<repo>/`.  The
//! resolver then looks for an `index.ilo` inside that directory and merges it.
//!
//! If the directory does not exist the resolver emits `ILO-P017` with a hint
//! to run `ilo add owner/repo`.

use semver::{Version, VersionReq};
use std::path::{Path, PathBuf};
use std::process::Command;

// ── host registry ──────────────────────────────────────────────────────────────

/// A recognised git hosting provider.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Host {
    GitHub,
    GitLab,
    Codeberg,
    /// A raw HTTPS base URL, e.g. `https://git.example.com`.
    Custom(String),
}

impl Host {
    /// The short name used as a cache-directory component and lockfile prefix.
    pub fn name(&self) -> &str {
        match self {
            Host::GitHub => "github",
            Host::GitLab => "gitlab",
            Host::Codeberg => "codeberg",
            Host::Custom(url) => url.as_str(),
        }
    }

    /// The HTTPS base URL (no trailing slash).
    pub fn base_url(&self) -> String {
        match self {
            Host::GitHub => "https://github.com".to_string(),
            Host::GitLab => "https://gitlab.com".to_string(),
            Host::Codeberg => "https://codeberg.org".to_string(),
            Host::Custom(url) => url.clone(),
        }
    }

    /// Build the clone URL for `owner/repo` on this host.
    pub fn clone_url(&self, owner: &str, repo: &str) -> String {
        format!("{}/{}/{}.git", self.base_url(), owner, repo)
    }

    /// Build the canonical web URL (no `.git`) for the lockfile.
    pub fn web_url(&self, owner: &str, repo: &str) -> String {
        format!("{}/{}/{}", self.base_url(), owner, repo)
    }
}

/// Parse an optional `host:` prefix from a spec string.
///
/// Returns `(Host, rest_of_spec)`.  If no recognised prefix is found the host
/// defaults to `Host::GitHub` and the full string is returned as `rest`.
fn parse_host_prefix(spec: &str) -> (Host, &str) {
    // Full HTTPS URLs are handled elsewhere; skip them here.
    if spec.starts_with("https://") || spec.starts_with("http://") {
        return (Host::GitHub, spec); // will be processed by URL strip logic
    }
    if let Some(rest) = spec.strip_prefix("github:") {
        return (Host::GitHub, rest);
    }
    if let Some(rest) = spec.strip_prefix("gitlab:") {
        return (Host::GitLab, rest);
    }
    if let Some(rest) = spec.strip_prefix("codeberg:") {
        return (Host::Codeberg, rest);
    }
    // No prefix — default to GitHub.
    (Host::GitHub, spec)
}

// ── public helpers ─────────────────────────────────────────────────────────────

/// Return the cache directory for a package.  Creates `~/.ilo/pkgs/` if needed.
/// Returns `None` when the home directory cannot be determined.
pub fn pkg_dir_for(host: &Host, owner: &str, repo: &str) -> Option<PathBuf> {
    let home = home_dir()?;
    Some(
        home.join(".ilo")
            .join("pkgs")
            .join(host.name())
            .join(owner)
            .join(repo),
    )
}

/// Parsed package specification returned by `parse_package_spec`.
#[derive(Debug, PartialEq)]
pub struct PackageSpec {
    pub host: Host,
    pub owner: String,
    pub repo: String,
    pub git_ref: Option<String>,
}

/// Parse a package spec into its components.
///
/// Accepted forms:
/// - `owner/repo`
/// - `owner/repo@ref`
/// - `github:owner/repo[@ref]`
/// - `gitlab:owner/repo[@ref]`
/// - `codeberg:owner/repo[@ref]`
/// - `https://github.com/owner/repo`  (full URL, host inferred)
/// - `https://gitlab.com/owner/repo`
/// - `https://codeberg.org/owner/repo`
///
/// Returns `None` when the input is not in a recognised form.
pub fn parse_package_spec(spec: &str) -> Option<PackageSpec> {
    // ── full HTTPS URL ────────────────────────────────────────────────────────
    if spec.starts_with("https://") || spec.starts_with("http://") {
        let (host, rest) = if let Some(r) = spec
            .strip_prefix("https://github.com/")
            .or_else(|| spec.strip_prefix("http://github.com/"))
        {
            (Host::GitHub, r)
        } else if let Some(r) = spec
            .strip_prefix("https://gitlab.com/")
            .or_else(|| spec.strip_prefix("http://gitlab.com/"))
        {
            (Host::GitLab, r)
        } else if let Some(r) = spec
            .strip_prefix("https://codeberg.org/")
            .or_else(|| spec.strip_prefix("http://codeberg.org/"))
        {
            (Host::Codeberg, r)
        } else {
            return None; // unknown host URL
        };
        let (slug, git_ref) = split_ref(rest);
        let (owner, repo) = slug.split_once('/')?;
        if owner.is_empty() || repo.is_empty() || repo.contains('/') {
            return None;
        }
        return Some(PackageSpec {
            host,
            owner: owner.to_string(),
            repo: repo.to_string(),
            git_ref: git_ref.map(str::to_string),
        });
    }

    // ── host-prefixed or bare spec ────────────────────────────────────────────
    let (host, rest) = parse_host_prefix(spec);
    let (slug, git_ref) = split_ref(rest);
    let (owner, repo) = slug.split_once('/')?;
    if owner.is_empty() || repo.is_empty() || repo.contains('/') {
        return None;
    }
    Some(PackageSpec {
        host,
        owner: owner.to_string(),
        repo: repo.to_string(),
        git_ref: git_ref.map(str::to_string),
    })
}

/// Return true when `path` looks like a package reference (`owner/repo` or
/// `host:owner/repo` or `owner/repo/sub/path.ilo`) rather than a local file.
///
/// Heuristic: the first component does not start with `.` or `/` and contains
/// no `.` (file extensions), which distinguishes it from `./lib.ilo` or
/// `../shared.ilo` or `relative/path.ilo`.
pub fn is_pkg_path(path: &str) -> bool {
    if path.starts_with('.') || path.starts_with('/') {
        return false;
    }
    // Strip a recognised host prefix before checking the first component.
    let stripped = if let Some(r) = path
        .strip_prefix("github:")
        .or_else(|| path.strip_prefix("gitlab:"))
        .or_else(|| path.strip_prefix("codeberg:"))
    {
        r
    } else {
        path
    };
    // Split off first component and check it looks like `owner` (no dots, no @).
    let first = stripped.split('/').next().unwrap_or("");
    !first.is_empty() && !first.contains('.')
}

/// Resolve a package `use` path to an absolute filesystem path.
///
/// `path` is the string from the `use` statement, e.g. `"myorg/helpers"`,
/// `"gitlab:myorg/helpers"`, or `"myorg/helpers/utils.ilo"`.  When the path
/// has no `.ilo` suffix the resolver appends `/index.ilo`.
///
/// Returns `Err(msg)` with a user-facing message when the package is not
/// installed (so the caller can wrap it in `ILO-P017`).
pub fn resolve_pkg_path(path: &str) -> Result<PathBuf, String> {
    // Strip a recognised host prefix.
    let (host, rest) = if let Some(r) = path.strip_prefix("github:") {
        (Host::GitHub, r)
    } else if let Some(r) = path.strip_prefix("gitlab:") {
        (Host::GitLab, r)
    } else if let Some(r) = path.strip_prefix("codeberg:") {
        (Host::Codeberg, r)
    } else {
        (Host::GitHub, path)
    };

    let (owner, rest2) = rest
        .split_once('/')
        .ok_or_else(|| format!("package path '{}' is not in owner/repo form", path))?;

    let (repo, sub) = if let Some((r, s)) = rest2.split_once('/') {
        (r, Some(s))
    } else {
        (rest2, None)
    };

    let cache_dir = pkg_dir_for(&host, owner, repo)
        .ok_or_else(|| "could not determine home directory for package cache".to_string())?;

    if !cache_dir.exists() {
        let hint_spec = if matches!(host, Host::GitHub) {
            format!("{owner}/{repo}")
        } else {
            format!("{}:{owner}/{repo}", host.name())
        };
        return Err(format!(
            "package '{hint_spec}' is not installed — run `ilo add {hint_spec}` first"
        ));
    }

    let file_path = match sub {
        Some(s) => cache_dir.join(s),
        None => cache_dir.join("index.ilo"),
    };

    Ok(file_path)
}

// ── semver constraint resolution ──────────────────────────────────────────────

/// Return true when `ref_str` is a semver constraint rather than a plain git ref.
///
/// Recognised forms:
/// - `^MAJOR`, `^MAJOR.MINOR`, `^MAJOR.MINOR.PATCH`  — caret (compatible)
/// - `~MAJOR.MINOR`, `~MAJOR.MINOR.PATCH`             — tilde (patch-compatible)
/// - `MAJOR.MINOR.PATCH`                              — exact semver triple
pub fn is_semver_constraint(ref_str: &str) -> bool {
    if ref_str.starts_with('^') || ref_str.starts_with('~') {
        return true;
    }
    // Bare X.Y.Z — three numeric components.
    let parts: Vec<&str> = ref_str.splitn(3, '.').collect();
    if parts.len() == 3 {
        return parts.iter().all(|p| p.chars().all(|c| c.is_ascii_digit()));
    }
    false
}

/// Resolve a semver constraint string to a concrete git tag that can be checked
/// out.  Queries the remote via `git ls-remote --tags` (no network clone needed).
///
/// Returns `Ok(tag_name)` for the highest matching version tag, or an error
/// message suitable for printing to stderr.
pub fn resolve_semver_ref(url: &str, constraint_str: &str) -> Result<String, String> {
    // Parse constraint — add `=` prefix for bare X.Y.Z so semver accepts it.
    let req_str = if constraint_str.starts_with('^') || constraint_str.starts_with('~') {
        constraint_str.to_string()
    } else {
        format!("={constraint_str}")
    };
    let req = VersionReq::parse(&req_str)
        .map_err(|e| format!("invalid semver constraint '{}': {}", constraint_str, e))?;

    // List tags from remote without cloning.
    let output = Command::new("git")
        .args(["ls-remote", "--tags", url])
        .output()
        .map_err(|e| format!("git ls-remote failed: {}", e))?;

    if !output.status.success() {
        return Err(format!(
            "git ls-remote returned non-zero for {}",
            url
        ));
    }

    let stdout = String::from_utf8_lossy(&output.stdout);

    // Parse lines like: `<sha>\trefs/tags/v1.2.3`
    // Skip `^{}` peeled entries — they are the dereferenced commit, but we want
    // the tag name; the resolver will checkout by tag name anyway.
    let mut best: Option<(Version, String)> = None;
    for line in stdout.lines() {
        let Some((_sha, tag_ref)) = line.split_once('\t') else {
            continue;
        };
        if tag_ref.ends_with("^{}") {
            continue;
        }
        let tag_name = tag_ref
            .strip_prefix("refs/tags/")
            .unwrap_or(tag_ref);

        // Accept `v1.2.3` or `1.2.3`.
        let version_str = tag_name.strip_prefix('v').unwrap_or(tag_name);
        let Ok(version) = Version::parse(version_str) else {
            continue;
        };

        if req.matches(&version) {
            let replace = match &best {
                None => true,
                Some((prev, _)) => version > *prev,
            };
            if replace {
                best = Some((version, tag_name.to_string()));
            }
        }
    }

    best.map(|(_, tag)| tag)
        .ok_or_else(|| format!("no tag found matching semver constraint '{}'", constraint_str))
}

// ── `ilo add` ──────────────────────────────────────────────────────────────────

/// Fetch (or re-fetch) a package into the local cache and update `ilo.lock`.
///
/// `spec` is one of:
/// - `owner/repo`
/// - `owner/repo@ref`
/// - `github:owner/repo[@ref]`
/// - `gitlab:owner/repo[@ref]`
/// - `codeberg:owner/repo[@ref]`
/// - `https://github.com/owner/repo` (full URL)
///
/// On success prints a one-line summary to stdout and returns `0`;
/// on failure prints to stderr and returns `1`.
pub fn cmd_add(spec: &str) -> i32 {
    let Some(pkg) = parse_package_spec(spec) else {
        eprintln!(
            "error: '{}' is not a valid package spec.\n\
             Expected: owner/repo  or  host:owner/repo  or  owner/repo@ref\n\
             Supported hosts: github (default), gitlab, codeberg",
            spec
        );
        return 1;
    };

    let PackageSpec {
        host,
        owner,
        repo,
        git_ref,
    } = pkg;

    let url = host.clone_url(&owner, &repo);

    // Resolve semver constraints to a concrete tag before cloning.
    let resolved_ref: Option<String> = match git_ref.as_deref() {
        Some(r) if is_semver_constraint(r) => {
            match resolve_semver_ref(&url, r) {
                Ok(tag) => {
                    println!("resolved semver '{}' → {}", r, tag);
                    Some(tag)
                }
                Err(e) => {
                    eprintln!("error: {}", e);
                    return 1;
                }
            }
        }
        _ => None,
    };
    let git_ref_str: &str = match &resolved_ref {
        Some(tag) => tag.as_str(),
        None => git_ref.as_deref().unwrap_or("HEAD"),
    };

    let Some(dest) = pkg_dir_for(&host, &owner, &repo) else {
        eprintln!("error: could not determine home directory");
        return 1;
    };

    // Remove stale cache so a re-add always gets a fresh shallow clone.
    if dest.exists() {
        if let Err(e) = std::fs::remove_dir_all(&dest) {
            eprintln!(
                "error: could not remove existing cache at {}: {}",
                dest.display(),
                e
            );
            return 1;
        }
    }

    if let Some(parent) = dest.parent() {
        if let Err(e) = std::fs::create_dir_all(parent) {
            eprintln!(
                "error: could not create cache directory {}: {}",
                parent.display(),
                e
            );
            return 1;
        }
    }

    // Shallow clone — depth 1.
    let clone_status = Command::new("git")
        .args([
            "clone",
            "--depth=1",
            "--single-branch",
            "--branch",
            git_ref_str,
            &url,
            dest.to_str().unwrap_or(""),
        ])
        .status();

    // If branch-targeted clone fails (e.g. ref is a SHA or tag not a branch),
    // fall back to a plain shallow clone and then checkout.
    let clone_ok = match clone_status {
        Ok(s) => s.success(),
        Err(_) => false,
    };

    if !clone_ok {
        // Fallback: clone default branch, then checkout the ref.
        let fallback = Command::new("git")
            .args(["clone", "--depth=1", &url, dest.to_str().unwrap_or("")])
            .status();
        match fallback {
            Ok(s) if s.success() => {}
            _ => {
                eprintln!("error: git clone failed for {}/{}", owner, repo);
                eprintln!("       Make sure the repo exists and you have network access.");
                return 1;
            }
        }
        if git_ref_str != "HEAD" {
            let checkout = Command::new("git")
                .args(["-C", dest.to_str().unwrap_or(""), "checkout", git_ref_str])
                .status();
            if !checkout.map(|s| s.success()).unwrap_or(false) {
                eprintln!(
                    "error: could not checkout ref '{}' in {}/{}",
                    git_ref_str, owner, repo
                );
                return 1;
            }
        }
    }

    // Read resolved commit SHA.
    let sha = resolved_sha(&dest);

    // The lockfile slug includes the host prefix (e.g. `github:owner/repo`).
    let lock_slug = format!("{}:{}/{}", host.name(), owner, repo);
    let web_url = host.web_url(&owner, &repo);

    // Update ilo.lock.
    update_lockfile(&lock_slug, &sha, &web_url);

    println!("added {} @ {}", lock_slug, sha);
    println!("  cache: {}", dest.display());
    0
}

// ── `ilo update` ──────────────────────────────────────────────────────────────

/// Re-fetch one or all packages from the lockfile.
pub fn cmd_update(package: Option<&str>) -> i32 {
    let lock_entries = read_lockfile();

    if lock_entries.is_empty() {
        println!("ilo.lock is empty — nothing to update.");
        return 0;
    }

    let mut exit = 0;

    for entry in &lock_entries {
        if let Some(pkg) = package {
            if entry.slug != pkg {
                continue;
            }
        }
        let rc = cmd_add(&entry.slug);
        if rc != 0 {
            exit = 1;
        }
    }

    exit
}

// ── lockfile ──────────────────────────────────────────────────────────────────

struct LockEntry {
    slug: String,
}

fn read_lockfile() -> Vec<LockEntry> {
    let path = std::path::Path::new("ilo.lock");
    let Ok(text) = std::fs::read_to_string(path) else {
        return Vec::new();
    };
    text.lines()
        .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
        .filter_map(|l| {
            let cols: Vec<&str> = l.splitn(3, '\t').collect();
            cols.first().map(|s| LockEntry {
                slug: s.to_string(),
            })
        })
        .collect()
}

/// Write or update the lockfile entry for a package.
fn update_lockfile(slug: &str, sha: &str, url: &str) {
    let path = Path::new("ilo.lock");

    let existing = if path.exists() {
        std::fs::read_to_string(path).unwrap_or_default()
    } else {
        String::new()
    };

    let new_line = format!("{slug}\t{sha}\t{url}");

    // Replace existing entry for this slug or append.
    let mut found = false;
    let mut lines: Vec<String> = existing
        .lines()
        .map(|l| {
            if !l.starts_with('#') {
                let cols: Vec<&str> = l.splitn(2, '\t').collect();
                if cols.first().copied() == Some(slug) {
                    found = true;
                    return new_line.clone();
                }
            }
            l.to_string()
        })
        .collect();

    if !found {
        if lines.is_empty() {
            lines.push("# ilo.lock — generated by `ilo add`; commit to source control".to_string());
        }
        lines.push(new_line);
    }

    let content = lines.join("\n") + "\n";
    if let Err(e) = std::fs::write(path, content) {
        eprintln!("warning: could not write ilo.lock: {}", e);
    }
}

// ── helpers ────────────────────────────────────────────────────────────────────

fn split_ref(s: &str) -> (&str, Option<&str>) {
    if let Some((slug, r)) = s.split_once('@') {
        (slug, Some(r))
    } else {
        (s, None)
    }
}

fn resolved_sha(repo_dir: &Path) -> String {
    Command::new("git")
        .args(["-C", repo_dir.to_str().unwrap_or("."), "rev-parse", "HEAD"])
        .output()
        .ok()
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| s.trim().to_string())
        .unwrap_or_else(|| "unknown".to_string())
}

fn home_dir() -> Option<PathBuf> {
    std::env::var_os("HOME").map(PathBuf::from)
}

// ── unit tests ─────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // ── parse_package_spec ────────────────────────────────────────────────────

    #[test]
    fn parse_simple_spec() {
        let r = parse_package_spec("myorg/helpers").unwrap();
        assert_eq!(r.host, Host::GitHub);
        assert_eq!(r.owner, "myorg");
        assert_eq!(r.repo, "helpers");
        assert_eq!(r.git_ref, None);
    }

    #[test]
    fn parse_spec_with_ref() {
        let r = parse_package_spec("myorg/helpers@v1.2").unwrap();
        assert_eq!(r.host, Host::GitHub);
        assert_eq!(r.owner, "myorg");
        assert_eq!(r.repo, "helpers");
        assert_eq!(r.git_ref, Some("v1.2".to_string()));
    }

    #[test]
    fn parse_explicit_github_prefix() {
        let r = parse_package_spec("github:myorg/helpers").unwrap();
        assert_eq!(r.host, Host::GitHub);
        assert_eq!(r.owner, "myorg");
        assert_eq!(r.repo, "helpers");
    }

    #[test]
    fn parse_gitlab_prefix() {
        let r = parse_package_spec("gitlab:myorg/myrepo").unwrap();
        assert_eq!(r.host, Host::GitLab);
        assert_eq!(r.owner, "myorg");
        assert_eq!(r.repo, "myrepo");
        assert_eq!(r.git_ref, None);
    }

    #[test]
    fn parse_gitlab_prefix_with_ref() {
        let r = parse_package_spec("gitlab:myorg/myrepo@main").unwrap();
        assert_eq!(r.host, Host::GitLab);
        assert_eq!(r.git_ref, Some("main".to_string()));
    }

    #[test]
    fn parse_codeberg_prefix() {
        let r = parse_package_spec("codeberg:user/repo").unwrap();
        assert_eq!(r.host, Host::Codeberg);
        assert_eq!(r.owner, "user");
        assert_eq!(r.repo, "repo");
    }

    #[test]
    fn parse_github_url() {
        let r = parse_package_spec("https://github.com/myorg/helpers").unwrap();
        assert_eq!(r.host, Host::GitHub);
        assert_eq!(r.owner, "myorg");
        assert_eq!(r.repo, "helpers");
    }

    #[test]
    fn parse_gitlab_url() {
        let r = parse_package_spec("https://gitlab.com/myorg/helpers").unwrap();
        assert_eq!(r.host, Host::GitLab);
        assert_eq!(r.owner, "myorg");
        assert_eq!(r.repo, "helpers");
    }

    #[test]
    fn parse_codeberg_url() {
        let r = parse_package_spec("https://codeberg.org/user/repo").unwrap();
        assert_eq!(r.host, Host::Codeberg);
        assert_eq!(r.owner, "user");
        assert_eq!(r.repo, "repo");
    }

    #[test]
    fn parse_bad_spec_returns_none() {
        assert!(parse_package_spec("notaslug").is_none());
        assert!(parse_package_spec("").is_none());
    }

    // ── host URLs ─────────────────────────────────────────────────────────────

    #[test]
    fn host_clone_urls() {
        assert_eq!(
            Host::GitHub.clone_url("org", "repo"),
            "https://github.com/org/repo.git"
        );
        assert_eq!(
            Host::GitLab.clone_url("org", "repo"),
            "https://gitlab.com/org/repo.git"
        );
        assert_eq!(
            Host::Codeberg.clone_url("user", "repo"),
            "https://codeberg.org/user/repo.git"
        );
    }

    // ── is_pkg_path ───────────────────────────────────────────────────────────

    #[test]
    fn is_pkg_path_true_for_owner_repo() {
        assert!(is_pkg_path("myorg/helpers"));
        assert!(is_pkg_path("myorg/helpers/utils.ilo"));
    }

    #[test]
    fn is_pkg_path_true_for_host_prefixed() {
        assert!(is_pkg_path("gitlab:myorg/helpers"));
        assert!(is_pkg_path("codeberg:user/repo"));
        assert!(is_pkg_path("github:myorg/helpers"));
    }

    #[test]
    fn is_pkg_path_false_for_local() {
        assert!(!is_pkg_path("./lib.ilo"));
        assert!(!is_pkg_path("../shared.ilo"));
        assert!(!is_pkg_path("/abs/path.ilo"));
        // `relative/path.ilo` — first component `relative` has no dot, so
        // this IS treated as a package path.  Unambiguous local files must use
        // a leading `./`.
        assert!(is_pkg_path("relative/path.ilo"));
    }

    #[test]
    fn semver_constraint_detection() {
        assert!(is_semver_constraint("^1.2"));
        assert!(is_semver_constraint("^1"));
        assert!(is_semver_constraint("~1.2.3"));
        assert!(is_semver_constraint("1.2.3"));
        // Not semver constraints:
        assert!(!is_semver_constraint("v1.2.3"));
        assert!(!is_semver_constraint("main"));
        assert!(!is_semver_constraint("HEAD"));
        assert!(!is_semver_constraint("abc123"));
        // Two-part bare version is NOT treated as semver (ambiguous git tag).
        assert!(!is_semver_constraint("1.2"));
    }

    #[test]
    fn is_pkg_path_false_for_relative_with_extension() {
        // `relative/path.ilo` — first component is `relative` (no dot), so is_pkg_path returns true.
        // This is intentional: the caller should try resolve_pkg_path which will
        // fail gracefully if the package is not installed.
        // (Local ilo files must use a leading `./` to be unambiguous.)
        assert!(is_pkg_path("relative/no-ext-dir"));
    }

    // ── pkg_dir_for ───────────────────────────────────────────────────────────

    #[test]
    fn pkg_dir_includes_host() {
        let dir = pkg_dir_for(&Host::GitLab, "org", "repo").unwrap();
        let s = dir.to_string_lossy();
        assert!(s.contains("gitlab"), "expected 'gitlab' in path, got {}", s);
        assert!(s.contains("org"));
        assert!(s.contains("repo"));
    }

    #[test]
    fn pkg_dir_github_default() {
        let dir = pkg_dir_for(&Host::GitHub, "org", "repo").unwrap();
        let s = dir.to_string_lossy();
        assert!(s.contains("github"), "expected 'github' in path, got {}", s);
    }
}
