//! Package registry: `ilo add <owner>/<repo>[@<ref>]` / `ilo update`.
//!
//! Cache layout:  `~/.ilo/pkgs/<owner>/<repo>/`
//! Lockfile:      `ilo.lock` in the project root (current working directory).
//!
//! The lock file is a plain-text tabular format — one resolved package per line:
//!
//! ```
//! # ilo.lock — generated by `ilo add`; commit to source control
//! owner/repo  <sha40>  https://github.com/owner/repo
//! ```
//!
//! Columns are tab-separated.  Lines starting with `#` are comments.
//!
//! ## `use "owner/repo"` resolution
//!
//! When `resolve_imports` sees a `use` path whose first component contains no
//! `.` (i.e. it looks like `owner/repo` not `./local.ilo`), it delegates to
//! `pkg_dir_for` which returns `~/.ilo/pkgs/<owner>/<repo>/`.  The resolver
//! then looks for an `index.ilo` inside that directory and merges it.
//!
//! If the directory does not exist the resolver emits `ILO-P017` with a hint
//! to run `ilo add owner/repo`.

use std::path::{Path, PathBuf};
use std::process::Command;

// ── public helpers ─────────────────────────────────────────────────────────────

/// Return the cache directory for a package.  Creates `~/.ilo/pkgs/` if needed.
/// Returns `None` when the home directory cannot be determined.
pub fn pkg_dir_for(owner: &str, repo: &str) -> Option<PathBuf> {
    let home = home_dir()?;
    Some(home.join(".ilo").join("pkgs").join(owner).join(repo))
}

/// Parse `owner/repo[@ref]` into `(owner, repo, Option<git_ref>)`.
/// Returns `None` when the input is not in a recognised form.
pub fn parse_package_spec(spec: &str) -> Option<(&str, &str, Option<&str>)> {
    // Strip a leading `https://github.com/` if someone pastes the URL.
    let spec = spec.strip_prefix("https://github.com/").unwrap_or(spec);

    let (slug, git_ref) = if let Some((s, r)) = spec.split_once('@') {
        (s, Some(r))
    } else {
        (spec, None)
    };

    let (owner, repo) = slug.split_once('/')?;

    // Must have exactly one `/` in the slug.
    if owner.is_empty() || repo.is_empty() || repo.contains('/') {
        return None;
    }

    Some((owner, repo, git_ref))
}

/// Return true when `path` looks like a package reference (`owner/repo` or
/// `owner/repo/sub/path.ilo`) rather than a local file path.
///
/// Heuristic: the first component does not start with `.` or `/` and contains
/// no `.` (file extensions), which distinguishes it from `./lib.ilo` or
/// `../shared.ilo` or `relative/path.ilo`.
pub fn is_pkg_path(path: &str) -> bool {
    if path.starts_with('.') || path.starts_with('/') {
        return false;
    }
    // Split off first component and check it looks like `owner` (no dots, no @).
    let first = path.split('/').next().unwrap_or("");
    !first.is_empty() && !first.contains('.')
}

/// Resolve a package `use` path to an absolute filesystem path.
///
/// `path` is the string from the `use` statement, e.g. `"myorg/helpers"` or
/// `"myorg/helpers/utils.ilo"`.  When the path has no `.ilo` suffix the
/// resolver appends `/index.ilo`.
///
/// Returns `Err(msg)` with a user-facing message when the package is not
/// installed (so the caller can wrap it in `ILO-P017`).
pub fn resolve_pkg_path(path: &str) -> Result<PathBuf, String> {
    // Strip leading slash/dots (already ruled out by is_pkg_path, but be safe).
    let (owner, rest) = path
        .split_once('/')
        .ok_or_else(|| format!("package path '{}' is not in owner/repo form", path))?;

    let (repo, sub) = if let Some((r, s)) = rest.split_once('/') {
        (r, Some(s))
    } else {
        (rest, None)
    };

    let cache_dir = pkg_dir_for(owner, repo)
        .ok_or_else(|| "could not determine home directory for package cache".to_string())?;

    if !cache_dir.exists() {
        return Err(format!(
            "package '{}/{repo}' is not installed — run `ilo add {owner}/{repo}` first",
            owner
        ));
    }

    let file_path = match sub {
        Some(s) => cache_dir.join(s),
        None => cache_dir.join("index.ilo"),
    };

    Ok(file_path)
}

// ── `ilo add` ──────────────────────────────────────────────────────────────────

/// Fetch (or re-fetch) a package into the local cache and update `ilo.lock`.
///
/// `spec` is `owner/repo` or `owner/repo@ref`.  On success prints a one-line
/// summary to stdout and returns `0`; on failure prints to stderr and returns `1`.
pub fn cmd_add(spec: &str) -> i32 {
    let Some((owner, repo, git_ref)) = parse_package_spec(spec) else {
        eprintln!(
            "error: '{}' is not a valid package spec.\n\
             Expected: owner/repo  or  owner/repo@ref",
            spec
        );
        return 1;
    };

    let git_ref = git_ref.unwrap_or("HEAD");
    let url = format!("https://github.com/{owner}/{repo}.git");

    let Some(dest) = pkg_dir_for(owner, repo) else {
        eprintln!("error: could not determine home directory");
        return 1;
    };

    // Remove stale cache so a re-add always gets a fresh shallow clone.
    if dest.exists() {
        if let Err(e) = std::fs::remove_dir_all(&dest) {
            eprintln!(
                "error: could not remove existing cache at {}: {}",
                dest.display(),
                e
            );
            return 1;
        }
    }

    if let Some(parent) = dest.parent() {
        if let Err(e) = std::fs::create_dir_all(parent) {
            eprintln!(
                "error: could not create cache directory {}: {}",
                parent.display(),
                e
            );
            return 1;
        }
    }

    // Shallow clone — depth 1.
    let clone_status = Command::new("git")
        .args([
            "clone",
            "--depth=1",
            "--single-branch",
            "--branch",
            git_ref,
            &url,
            dest.to_str().unwrap_or(""),
        ])
        .status();

    // If branch-targeted clone fails (e.g. ref is a SHA or tag not a branch),
    // fall back to a plain shallow clone and then checkout.
    let clone_ok = match clone_status {
        Ok(s) => s.success(),
        Err(_) => false,
    };

    if !clone_ok {
        // Fallback: clone default branch, then checkout the ref.
        let fallback = Command::new("git")
            .args(["clone", "--depth=1", &url, dest.to_str().unwrap_or("")])
            .status();
        match fallback {
            Ok(s) if s.success() => {}
            _ => {
                eprintln!("error: git clone failed for {}/{}", owner, repo);
                eprintln!("       Make sure the repo exists and you have network access.");
                return 1;
            }
        }
        if git_ref != "HEAD" {
            let checkout = Command::new("git")
                .args(["-C", dest.to_str().unwrap_or(""), "checkout", git_ref])
                .status();
            if !checkout.map(|s| s.success()).unwrap_or(false) {
                eprintln!(
                    "error: could not checkout ref '{}' in {}/{}",
                    git_ref, owner, repo
                );
                return 1;
            }
        }
    }

    // Read resolved commit SHA.
    let sha = resolved_sha(&dest);

    // Update ilo.lock.
    update_lockfile(
        owner,
        repo,
        &sha,
        &format!("https://github.com/{owner}/{repo}"),
    );

    println!("added {owner}/{repo} @ {sha}");
    println!("  cache: {}", dest.display());
    0
}

// ── `ilo update` ──────────────────────────────────────────────────────────────

/// Re-fetch one or all packages from the lockfile.
pub fn cmd_update(package: Option<&str>) -> i32 {
    let lock_entries = read_lockfile();

    if lock_entries.is_empty() {
        println!("ilo.lock is empty — nothing to update.");
        return 0;
    }

    let mut exit = 0;

    for entry in &lock_entries {
        if let Some(pkg) = package {
            if entry.slug != pkg {
                continue;
            }
        }
        let rc = cmd_add(&entry.slug);
        if rc != 0 {
            exit = 1;
        }
    }

    exit
}

// ── lockfile ──────────────────────────────────────────────────────────────────

struct LockEntry {
    slug: String,
}

fn read_lockfile() -> Vec<LockEntry> {
    let path = std::path::Path::new("ilo.lock");
    let Ok(text) = std::fs::read_to_string(path) else {
        return Vec::new();
    };
    text.lines()
        .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
        .filter_map(|l| {
            let cols: Vec<&str> = l.splitn(3, '\t').collect();
            cols.first().map(|s| LockEntry {
                slug: s.to_string(),
            })
        })
        .collect()
}

/// Write or update the lockfile entry for a package.
fn update_lockfile(owner: &str, repo: &str, sha: &str, url: &str) {
    let slug = format!("{owner}/{repo}");
    let path = Path::new("ilo.lock");

    let existing = if path.exists() {
        std::fs::read_to_string(path).unwrap_or_default()
    } else {
        String::new()
    };

    let new_line = format!("{slug}\t{sha}\t{url}");

    // Replace existing entry for this slug or append.
    let mut found = false;
    let mut lines: Vec<String> = existing
        .lines()
        .map(|l| {
            if !l.starts_with('#') {
                let cols: Vec<&str> = l.splitn(2, '\t').collect();
                if cols.first().copied() == Some(slug.as_str()) {
                    found = true;
                    return new_line.clone();
                }
            }
            l.to_string()
        })
        .collect();

    if !found {
        if lines.is_empty() {
            lines.push("# ilo.lock — generated by `ilo add`; commit to source control".to_string());
        }
        lines.push(new_line);
    }

    let content = lines.join("\n") + "\n";
    if let Err(e) = std::fs::write(path, content) {
        eprintln!("warning: could not write ilo.lock: {}", e);
    }
}

// ── helpers ────────────────────────────────────────────────────────────────────

fn resolved_sha(repo_dir: &Path) -> String {
    Command::new("git")
        .args(["-C", repo_dir.to_str().unwrap_or("."), "rev-parse", "HEAD"])
        .output()
        .ok()
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| s.trim().to_string())
        .unwrap_or_else(|| "unknown".to_string())
}

fn home_dir() -> Option<PathBuf> {
    std::env::var_os("HOME").map(PathBuf::from)
}

// ── unit tests ─────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_simple_spec() {
        let r = parse_package_spec("myorg/helpers");
        assert_eq!(r, Some(("myorg", "helpers", None)));
    }

    #[test]
    fn parse_spec_with_ref() {
        let r = parse_package_spec("myorg/helpers@v1.2");
        assert_eq!(r, Some(("myorg", "helpers", Some("v1.2"))));
    }

    #[test]
    fn parse_github_url() {
        let r = parse_package_spec("https://github.com/myorg/helpers");
        assert_eq!(r, Some(("myorg", "helpers", None)));
    }

    #[test]
    fn parse_bad_spec_returns_none() {
        assert!(parse_package_spec("notaslug").is_none());
        assert!(parse_package_spec("").is_none());
    }

    #[test]
    fn is_pkg_path_true_for_owner_repo() {
        assert!(is_pkg_path("myorg/helpers"));
        assert!(is_pkg_path("myorg/helpers/utils.ilo"));
    }

    #[test]
    fn is_pkg_path_false_for_local() {
        assert!(!is_pkg_path("./lib.ilo"));
        assert!(!is_pkg_path("../shared.ilo"));
        assert!(!is_pkg_path("/abs/path.ilo"));
        // `relative/path.ilo` — first component `relative` has no dot, so
        // this IS treated as a package path.  Unambiguous local files must use
        // a leading `./`.
        assert!(is_pkg_path("relative/path.ilo"));
    }

    #[test]
    fn is_pkg_path_false_for_relative_with_extension() {
        // `relative/path.ilo` — first component is `relative` (no dot), so is_pkg_path returns true.
        // This is intentional: the caller should try resolve_pkg_path which will
        // fail gracefully if the package is not installed.
        // (Local ilo files must use a leading `./` to be unambiguous.)
        assert!(is_pkg_path("relative/no-ext-dir"));
    }
}
